import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Menu from '../components/menu';
import styled from 'styled-components';
import { AuthProvider } from '../firebase/context';
import { useRouter } from 'next/router';

const Content = styled.div`
  margin: 2rem;
`;

function MyApp({ Component, pageProps }: AppProps) {
  const menuPoints = [
    { linkName: 'home', href: '/' },
    { linkName: 'konzerte', href: 'konzerte' },
    { linkName: 'personal', href: 'personal' },
  ];

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Stricker Intern</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {router.pathname !== '/' && !router.pathname.includes('authes/') && (
        <Menu menuPoints={menuPoints} />
      )} */}
      {/* <AuthProvider> */}
      <Content>
        <Component {...pageProps} />
      </Content>
      {/* </AuthProvider> */}
    </>
  );
}

export default MyApp;
